
export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const ADD_PLACES = "ADD_PLACES";
export const SHOW_ONLY_FAVORITES = "SHOW_ONLY_FAVORITES";
export const TOGGLE_DARK_MODE = "TOGGLE_DARK_MODE";
export const ADD_MYPLACES = "ADD_MYPLACES";
